### ISSUE TITLE
Please mention what's new in the builds

### ISSUE THREAD

**Issue by nesdnuma** [CadQuery/cadquery-contrib#17]
Hello,

As there are often new builds, it would be useful to know what's new in each new build.

Thank you for considering this request.

**Comment by jmwright** [comment]
@nesdnuma Are you talking about the main CadQuery project? This is just a repository of examples.

**Comment by nesdnuma** [comment]
Too many tabs open on my browser, sorry. This was intended for CQ-Editor...
